// Centralised category-icon registry. Icons are stored in the DB as their
// stable Lucide name string (e.g. "Utensils"). Purely presentational.
import {
  Utensils,
  UtensilsCrossed,
  Coffee,
  Pizza,
  Beef,
  Apple,
  Wine,
  CupSoda,
  Soup,
  Sandwich,
  IceCreamCone,
  ShoppingCart,
  ShoppingBag,
  Store,
  Shirt,
  Gift,
  Tag,
  Package,
  Gem,
  Home,
  House,
  Building,
  Building2,
  Sofa,
  Bed,
  Lamp,
  Bath,
  Wrench,
  Paintbrush,
  Trees,
  Car,
  Bus,
  Train,
  Bike,
  Fuel,
  Plane,
  Ship,
  CarTaxiFront,
  HeartPulse,
  Pill,
  Stethoscope,
  Activity,
  Dumbbell,
  Cross,
  Syringe,
  Gamepad2,
  Clapperboard,
  Film,
  Music,
  Tv,
  Headphones,
  Ticket,
  PartyPopper,
  Popcorn,
  GraduationCap,
  BookOpen,
  Book,
  Library,
  Pencil,
  School,
  NotebookPen,
  Briefcase,
  Laptop,
  Presentation,
  Handshake,
  Target,
  Users,
  Wallet,
  Landmark,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  Percent,
  TrendingUp,
  TrendingDown,
  Receipt,
  ReceiptText,
  BadgeDollarSign,
  CircleDollarSign,
  HandCoins,
  MapPin,
  Luggage,
  Hotel,
  Compass,
  Mountain,
  TentTree,
  Smartphone,
  Wifi,
  Monitor,
  Cpu,
  HardDrive,
  Cloud,
  Bot,
  Sparkles,
  Scissors,
  Baby,
  PawPrint,
  Flower2,
  Camera,
  GlassWater,
  Recycle,
  Lightbulb,
  Zap,
  Droplets,
  Flame,
  Phone,
  ShieldCheck,
  Repeat,
  MoreHorizontal,
  Boxes,
  Star,
  Bookmark,
  Hash,
  HelpCircle,
} from 'lucide-react'

/** [name, Component, keywords, group] */
const RAW = [
  // Food & Dining
  [Utensils, 'food eat dining restaurant meal lunch dinner', 'Food'],
  [UtensilsCrossed, 'food restaurant cutlery dining', 'Food'],
  [Coffee, 'coffee cafe tea drink beverage morning', 'Food'],
  [Pizza, 'pizza fast food takeaway delivery', 'Food'],
  [Beef, 'meat food grocery butcher', 'Food'],
  [Apple, 'fruit healthy grocery snack', 'Food'],
  [Wine, 'wine alcohol drink bar', 'Food'],
  [CupSoda, 'soda drink beverage juice', 'Food'],
  [Soup, 'soup food broth meal', 'Food'],
  [Sandwich, 'sandwich lunch food snack', 'Food'],
  [IceCreamCone, 'ice cream dessert sweet treat', 'Food'],
  // Shopping
  [ShoppingCart, 'shopping cart grocery groceries supermarket buy', 'Shopping'],
  [ShoppingBag, 'shopping bag store retail purchase', 'Shopping'],
  [Store, 'store shop retail market', 'Shopping'],
  [Shirt, 'clothing clothes apparel fashion wardrobe', 'Shopping'],
  [Gift, 'gift present bonus reward birthday', 'Shopping'],
  [Tag, 'tag price label sale discount', 'Shopping'],
  [Package, 'package parcel delivery order box', 'Shopping'],
  [Gem, 'jewellery jewelry gem luxury diamond', 'Shopping'],
  // Home
  [Home, 'home house rent mortgage housing', 'Home'],
  [House, 'house home property rent mortgage', 'Home'],
  [Building, 'building apartment flat rent', 'Home'],
  [Building2, 'building rental property office apartment', 'Home'],
  [Sofa, 'furniture sofa couch living room home', 'Home'],
  [Bed, 'bed bedroom furniture sleep mattress', 'Home'],
  [Lamp, 'lamp light furniture decor home', 'Home'],
  [Bath, 'bath bathroom plumbing home', 'Home'],
  [Wrench, 'repair maintenance tools fix home', 'Home'],
  [Paintbrush, 'paint renovation decor home improvement', 'Home'],
  [Trees, 'garden plants outdoor yard landscaping', 'Home'],
  // Transport
  [Car, 'car vehicle transport auto drive', 'Transport'],
  [Bus, 'bus public transport commute', 'Transport'],
  [Train, 'train metro rail commute transport', 'Transport'],
  [Bike, 'bike bicycle cycle transport', 'Transport'],
  [Fuel, 'fuel petrol gas diesel car', 'Transport'],
  [Plane, 'plane flight travel airfare airport', 'Transport'],
  [Ship, 'ship boat ferry cruise travel', 'Transport'],
  [CarTaxiFront, 'taxi cab uber ola ride', 'Transport'],
  // Health
  [HeartPulse, 'health medical healthcare hospital heart', 'Health'],
  [Pill, 'medicine pharmacy pills medication drug', 'Health'],
  [Stethoscope, 'doctor clinic checkup medical', 'Health'],
  [Activity, 'fitness health activity pulse', 'Health'],
  [Dumbbell, 'gym fitness workout exercise sport', 'Health'],
  [Cross, 'pharmacy medical clinic aid', 'Health'],
  [Syringe, 'vaccine injection medical shot', 'Health'],
  // Entertainment
  [Gamepad2, 'game gaming entertainment play console video', 'Entertainment'],
  [Clapperboard, 'movie cinema film entertainment', 'Entertainment'],
  [Film, 'film movie video streaming', 'Entertainment'],
  [Music, 'music song audio spotify concert', 'Entertainment'],
  [Tv, 'tv television streaming netflix show', 'Entertainment'],
  [Headphones, 'headphones audio music podcast', 'Entertainment'],
  [Ticket, 'ticket event concert show booking', 'Entertainment'],
  [PartyPopper, 'party celebration event fun', 'Entertainment'],
  [Popcorn, 'popcorn movie cinema snack', 'Entertainment'],
  // Education
  [GraduationCap, 'education school college university tuition degree fees', 'Education'],
  [BookOpen, 'book reading study education course', 'Education'],
  [Book, 'book textbook study education library', 'Education'],
  [Library, 'library books study education', 'Education'],
  [Pencil, 'pencil write notes stationery school', 'Education'],
  [School, 'school class education students', 'Education'],
  [NotebookPen, 'notebook notes study course writing', 'Education'],
  // Work & Business
  [Briefcase, 'work business job office salary career', 'Work'],
  [Laptop, 'laptop computer work tech freelance', 'Work'],
  [Presentation, 'presentation meeting business work', 'Work'],
  [Handshake, 'deal business partnership client', 'Work'],
  [Target, 'goal target objective business', 'Work'],
  [Users, 'team people clients staff hr', 'Work'],
  // Finance
  [Wallet, 'wallet salary income money cash pay', 'Finance'],
  [Landmark, 'bank finance institution account', 'Finance'],
  [PiggyBank, 'savings piggy bank deposit fund', 'Finance'],
  [CreditCard, 'card credit debit payment bank', 'Finance'],
  [Banknote, 'cash money note currency bill', 'Finance'],
  [Coins, 'coins money change savings cash', 'Finance'],
  [Percent, 'interest percent rate discount tax', 'Finance'],
  [TrendingUp, 'investment growth profit stocks gain returns', 'Finance'],
  [TrendingDown, 'loss decline expense drop', 'Finance'],
  [Receipt, 'receipt bill invoice expense payment', 'Finance'],
  [ReceiptText, 'bill invoice receipt utilities statement', 'Finance'],
  [BadgeDollarSign, 'salary income dollar pay earnings', 'Finance'],
  [CircleDollarSign, 'money dollar cash payment', 'Finance'],
  [HandCoins, 'lending loan money given repayment', 'Finance'],
  // Travel
  [MapPin, 'location travel place map trip', 'Travel'],
  [Luggage, 'luggage suitcase travel trip vacation', 'Travel'],
  [Hotel, 'hotel stay accommodation lodging travel', 'Travel'],
  [Compass, 'compass explore navigation travel adventure', 'Travel'],
  [Mountain, 'mountain hiking outdoor trek trip', 'Travel'],
  [TentTree, 'camping tent outdoor trip nature', 'Travel'],
  // Technology
  [Smartphone, 'phone mobile smartphone electronics device', 'Technology'],
  [Wifi, 'wifi internet broadband network connection', 'Technology'],
  [Monitor, 'monitor screen computer display electronics', 'Technology'],
  [Cpu, 'cpu processor hardware pc electronics', 'Technology'],
  [HardDrive, 'storage drive backup disk data', 'Technology'],
  [Cloud, 'cloud storage subscription saas hosting', 'Technology'],
  [Bot, 'ai bot automation software', 'Technology'],
  // Lifestyle
  [Sparkles, 'beauty spa self care lifestyle', 'Lifestyle'],
  [Scissors, 'haircut salon barber grooming', 'Lifestyle'],
  [Baby, 'baby childcare kids family', 'Lifestyle'],
  [PawPrint, 'pet dog cat animal vet', 'Lifestyle'],
  [Flower2, 'flowers gift plants decor', 'Lifestyle'],
  [Camera, 'camera photography hobby', 'Lifestyle'],
  [GlassWater, 'water hydration drink', 'Lifestyle'],
  [Recycle, 'recycle eco waste environment', 'Lifestyle'],
  // Bills & Utilities
  [Lightbulb, 'electricity utilities power bulb bill', 'Bills'],
  [Zap, 'electricity power energy bill', 'Bills'],
  [Droplets, 'water bill utilities plumbing', 'Bills'],
  [Flame, 'gas heating fuel utilities bill', 'Bills'],
  [Phone, 'phone mobile bill call recharge', 'Bills'],
  [ShieldCheck, 'insurance protection security cover premium', 'Bills'],
  [Repeat, 'subscription recurring renewal membership', 'Bills'],
  // Other
  [MoreHorizontal, 'other misc general uncategorized', 'Other'],
  [Boxes, 'misc stuff general other storage', 'Other'],
  [Star, 'favourite starred important other', 'Other'],
  [Bookmark, 'saved bookmark note other', 'Other'],
  [Hash, 'tag number category other', 'Other'],
  [HelpCircle, 'unknown other misc question', 'Other'],
]

export const ICON_LIST = RAW.map(([Icon, keywords, group]) => ({
  name: Icon.displayName || Icon.name,
  Icon,
  keywords,
  group,
}))

const REGISTRY = new Map(ICON_LIST.map((e) => [e.name, e.Icon]))

export const ICON_GROUPS = ['All', ...Array.from(new Set(ICON_LIST.map((e) => e.group)))]

export const FALLBACK_ICON_NAME = 'MoreHorizontal'

/** Resolve a stored icon name to a Lucide component (never throws). */
export function resolveIcon(name) {
  return REGISTRY.get(name) || REGISTRY.get(FALLBACK_ICON_NAME) || MoreHorizontal
}

export function isKnownIcon(name) {
  return REGISTRY.has(name)
}

/** Live search across name + keywords + group. */
export function searchIcons(query, group = 'All') {
  const q = query.trim().toLowerCase()
  return ICON_LIST.filter((e) => {
    if (group !== 'All' && e.group !== group) return false
    if (!q) return true
    return e.name.toLowerCase().includes(q) || e.keywords.includes(q) || e.keywords.split(' ').some((k) => k.startsWith(q)) || e.group.toLowerCase().includes(q)
  })
}

// Keyword → icon suggestions for auto-suggesting on category name entry.
const SUGGEST_RULES = [
  [/rent|mortgage|hous/i, 'Home'],
  [/salary|pay ?roll|wage/i, 'Wallet'],
  [/freelanc|contract|gig/i, 'Laptop'],
  [/business|company|firm/i, 'Briefcase'],
  [/bonus|reward|incentive/i, 'Gift'],
  [/interest/i, 'Percent'],
  [/invest|stock|dividend|mutual|sip/i, 'TrendingUp'],
  [/rental|tenant|lease/i, 'Building2'],
  [/grocer|supermarket|vegetab|kirana/i, 'ShoppingCart'],
  [/restaurant|dining|dinner|lunch|meal|swiggy|zomato/i, 'Utensils'],
  [/coffee|cafe|tea|starbucks/i, 'Coffee'],
  [/food|snack|eat/i, 'Utensils'],
  [/fuel|petrol|diesel|gas station/i, 'Fuel'],
  [/cab|taxi|uber|ola|ride/i, 'CarTaxiFront'],
  [/car|vehicle|auto/i, 'Car'],
  [/bus|metro|train|transit|commute/i, 'Train'],
  [/flight|airfare|air ?ticket|plane/i, 'Plane'],
  [/travel|trip|vacation|holiday|tour/i, 'Luggage'],
  [/hotel|stay|lodg|airbnb/i, 'Hotel'],
  [/movie|cinema|netflix|theatre/i, 'Clapperboard'],
  [/game|gaming|xbox|playstation|steam/i, 'Gamepad2'],
  [/music|spotify|concert/i, 'Music'],
  [/subscription|membership|recurring|prime/i, 'Repeat'],
  [/internet|broadband|wifi/i, 'Wifi'],
  [/phone|mobile|recharge|airtel|jio/i, 'Phone'],
  [/electric|power|current/i, 'Lightbulb'],
  [/water bill|water/i, 'Droplets'],
  [/util|bill/i, 'ReceiptText'],
  [/insurance|premium|policy/i, 'ShieldCheck'],
  [/health|medical|hospital|clinic|doctor|pharmac|medicine/i, 'HeartPulse'],
  [/gym|fitness|workout|yoga/i, 'Dumbbell'],
  [/school|college|university|tuition|course|educat|class|book|fees/i, 'GraduationCap'],
  [/shop|clothes|clothing|apparel|fashion|amazon|flipkart/i, 'ShoppingBag'],
  [/electron|gadget|laptop|computer|device/i, 'Smartphone'],
  [/gift|present/i, 'Gift'],
  [/pet|dog|cat|vet/i, 'PawPrint'],
  [/salon|haircut|barber|beauty|spa/i, 'Scissors'],
  [/child|baby|kids|daycare/i, 'Baby'],
  [/loan|lend|borrow|emi|repay/i, 'HandCoins'],
  [/save|saving|deposit/i, 'PiggyBank'],
  [/bank|account/i, 'Landmark'],
  [/tax|gst|tds/i, 'Percent'],
]

export function suggestIcon(categoryName) {
  const name = (categoryName || '').trim()
  if (!name) return null
  for (const [re, icon] of SUGGEST_RULES) if (re.test(name)) return icon
  return null
}
