import { Link } from 'react-router-dom'
import LegalPageLayout from './components/LegalPageLayout'
import { BUSINESS_INFO, isConfigured } from '../../config/businessConfig'

const brand = BUSINESS_INFO.brandName

export default function PrivacyPolicyPage() {
  const sections = [
    {
      id: 'introduction',
      heading: '1. Introduction',
      content: [
        `This Privacy Policy explains what information ${brand} collects when you use the Service, and how that information is used and protected. It applies to everyone who creates an account or otherwise uses ${brand}.`,
      ],
    },
    {
      id: 'information-we-collect',
      heading: '2. Information We Collect',
      content: [
        'We collect information in three broad categories: information you provide when creating your account, financial information you choose to enter, and basic technical information generated by your use of the Service.',
      ],
    },
    {
      id: 'account-information',
      heading: '3. Account Information',
      content: [
        {
          bullets: [
            'Your name and email address, provided at sign-up or via Google sign-in.',
            'An optional profile photo, if you upload one.',
            'Preferences such as currency and timezone.',
          ],
        },
      ],
    },
    {
      id: 'financial-information',
      heading: '4. Financial Information Entered by Users',
      content: [
        `${brand} lets you record accounts, transactions, budgets, savings goals, bills and recurring payments, and lending records that you enter yourself. This information is self-reported by you — ${brand} does not connect to, or retrieve data directly from, any bank, card network, or financial institution on your behalf.`,
      ],
    },
    {
      id: 'transaction-data',
      heading: '5. Transaction Data',
      content: [
        'Transaction records you create (amounts, dates, categories, descriptions, and notes) are stored so the Service can show your balances, budgets, analytics, and reports back to you.',
      ],
    },
    {
      id: 'device-usage',
      heading: '6. Device and Usage Information',
      content: [
        'Like most web applications, our infrastructure providers may log basic technical information such as IP address, browser type, and request timestamps for security and reliability purposes.',
      ],
    },
    {
      id: 'how-we-use',
      heading: '7. How We Use Information',
      content: [
        {
          bullets: [
            'To provide, maintain, and secure the Service and your account.',
            'To calculate and display your financial summaries, budgets, analytics, and reports.',
            'To process subscription payments and manage your plan.',
            'To respond to support requests you send us, including through the Contact page.',
            'To send account-related emails (such as email verification or password reset) triggered by your own actions.',
          ],
        },
      ],
    },
    {
      id: 'authentication',
      heading: '8. Authentication',
      content: [
        'Account sign-in (email/password and Google sign-in) is handled by Supabase Auth. Your session is kept in your browser\'s local storage so you stay signed in between visits; it is not shared with any other site.',
      ],
    },
    {
      id: 'payment-processing',
      heading: '9. Payment Processing',
      content: [
        `${brand} does not collect or store your full card number, UPI PIN, net-banking credentials, or any other sensitive payment credential. Subscription payments are handled entirely by our payment gateway, Razorpay — see the next section.`,
      ],
    },
    {
      id: 'razorpay',
      heading: '10. Razorpay',
      content: [
        'When you subscribe to a paid plan, your payment details are collected and processed directly by Razorpay through its own hosted checkout. Razorpay shares back with us only what is necessary to activate your subscription, such as a subscription reference ID and payment status — never your full card or bank details. Razorpay\'s handling of your payment information is governed by Razorpay\'s own privacy policy.',
      ],
    },
    {
      id: 'supabase',
      heading: '11. Supabase',
      content: [
        `${brand} is built on Supabase, which provides our database, authentication, and file storage infrastructure. All the account and financial information described above is stored in a Supabase-hosted database. Access to your data is restricted at the database level so that, by default, only you (and, where applicable, an authorised ${brand} administrator acting for support or compliance purposes) can access it.`,
      ],
    },
    {
      id: 'cookies',
      heading: '12. Cookies and Similar Technologies',
      content: [
        `${brand} itself does not use advertising or tracking cookies. Your signed-in session is kept using your browser's local storage rather than a tracking cookie. Our infrastructure providers (such as Supabase and Razorpay) may use their own essential cookies or similar technologies as part of operating their services.`,
      ],
    },
    {
      id: 'security',
      heading: '13. Data Security',
      content: [
        'We restrict access to your data using database-level access rules so that each user can only read and modify their own records, and apply the same principle to administrative access. No method of storage or transmission is completely secure, and we cannot guarantee absolute security.',
      ],
    },
    {
      id: 'retention',
      heading: '14. Data Retention',
      content: [
        'We retain your account and financial data for as long as your account remains active, so that the Service can continue to work for you. If you delete your account, associated personal data is removed or anonymised, other than records we are required to keep for legitimate accounting, security, or legal purposes.',
      ],
    },
    {
      id: 'data-sharing',
      heading: '15. Data Sharing',
      content: [
        `We do not sell your personal or financial information. We share information only with the service providers described in this policy (Supabase and Razorpay) to the extent needed to operate ${brand}, or where required by law.`,
      ],
    },
    {
      id: 'third-party-services',
      heading: '16. Third-Party Services',
      content: [
        'The only third-party services this application integrates with today are Supabase (infrastructure) and Razorpay (payments). We do not use third-party advertising networks or analytics/tracking pixels within the Service.',
      ],
    },
    {
      id: 'user-rights',
      heading: '17. User Rights',
      content: [
        'You can view and edit most of your account and financial information directly within the Service at any time (Settings, Accounts, Transactions, and related pages). You may also contact us to request a copy of your data or to ask questions about how it is handled.',
      ],
    },
    {
      id: 'account-deletion',
      heading: '18. Account Deletion',
      content: [
        <>
          To request deletion of your account and associated data, please reach out via our{' '}
          <Link to="/contact" className="font-medium text-brand-700 underline dark:text-brand-400">
            Contact page
          </Link>
          . We will process verified requests in line with any legal or accounting retention obligations that apply.
        </>,
      ],
    },
    {
      id: 'childrens-privacy',
      heading: '19. Children\'s Privacy',
      content: [
        `${brand} is not directed at children and is not intended for use by anyone below the legal age of consent for data processing in their jurisdiction.`,
      ],
    },
    {
      id: 'changes',
      heading: '20. Changes to This Privacy Policy',
      content: [
        'We may update this Privacy Policy from time to time. Material changes will be reflected by an updated "Last updated" date on this page.',
      ],
    },
    {
      id: 'contact',
      heading: '21. Contact Us',
      content: [
        isConfigured(BUSINESS_INFO.supportEmail)
          ? `Questions about this Privacy Policy, or requests regarding your data, can be sent to ${BUSINESS_INFO.supportEmail}, or via our Contact page.`
          : 'Questions about this Privacy Policy, or requests regarding your data, can be sent to us via our Contact page.',
      ],
    },
  ]

  return (
    <LegalPageLayout
      title="Privacy Policy"
      description="Learn how MoneyFlow handles information when you use our service."
      sections={sections}
    />
  )
}
